apiVersion: argoproj.io/v1alpha1
kind: Workflow                  
metadata:
  generateName: homepage-test-  
spec:
  entrypoint: homepage-up-and-running 
  templates:
    - name: homepage-up-and-running
      script:
        image: broadinstitute/python-requests:2.7
        command: [python]
        source: |
          import requests
          
          try:
            r = requests.get("https://dev.eodatahub.org.uk/")
            print(r.status_code)

          except request.ConnectionError:
            print("Failed to connect")
            
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 100m